---
header-includes:
    - '\defaultfontfeatures{Extension = .otf}'
    - '\usepackage{fontawesome}'
    - '\pagenumbering{gobble}'
geometry: margin=2.5cm
output:
  pdf_document: 
    extra_dependencies: ["marvosym"]
    keep_tex: true
    includes:
      in_header: columns.tex
    latex_engine: xelatex
---

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.4\textwidth}"}
#  Aleksander Borowski

:::

::: {.col data-latex="{0.2\textwidth}"}
\ 
:::

::: {.col data-latex="{0.4\textwidth}"}
\flushright{\textbf{Devops developer}}
:::

::::::

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.4\textwidth}"}
\Telefon \ \emph{Given upon request}

\faHome \ Wrocław, Dolnośląskie - Poland
\ \
:::

::: {.col data-latex="{0.2\textwidth}"}
\ 
:::

::: {.col data-latex="{0.4\textwidth}"}
\Letter \ aleksander.borowski.01@gmail.com

[\faGithub \ github.com/happyRip](https://github.com/happyRip){target="_blank"}
\ \
:::

::::::

---

## Experience

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.2\textwidth}"}
*Feb 2022 - present*
:::

::: {.col data-latex="{0.05\textwidth}"}
\ 
:::

::: {.col data-latex="{0.75\textwidth}"}
### DevOps Working Student

> *Nokia Wrocław*

I'm part of an international SCM team mainly working with automation and cloud solutions.
My duties consist of [Jenkins](https://www.jenkins.io) and [OpenStack](https://www.openstack.org/)
management as well as writing [Groovy](https://groovy-lang.org/) and bash scripts.
\ \
:::

::::::

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.2\textwidth}"}
*Sep 2021 - Jan 2022*
:::

::: {.col data-latex="{0.05\textwidth}"}
\ 
:::

::: {.col data-latex="{0.75\textwidth}"}
### DevOps Working Student

> *Nokia Wrocław*

I'm responsble for managing and hardening embedded linux systems using
[the&nbsp;Yocto&nbsp;Project](https://www.yoctoproject.org/) stack.
Here I've learned core Agile principles and common Jira workflow in practice.
\ \
:::

::::::

---

## Education

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.2\textwidth}"}
2019 - present
:::

::: {.col data-latex="{0.05\textwidth}"}
\ 
:::

::: {.col data-latex="{0.75\textwidth}"}
### Electronics and Telecommunication

> *Wrocław University of Technology,*
>
> *Faculty of Microsystem Electronics and Photonics*
\ \
:::

::::::

---

## Projects

:::::::::::: {.cols data-latex=""}

::::::::: {.col data-latex="{0.2\textwidth}"}
2022

#### Technologies:

Elixir *([Phoenix](https://www.phoenixframework.org/))*,
[Docker](https://www.docker.com/),
[GitHub Actions](https://github.com/features/actions)
:::::::::

::::::::: {.col data-latex="{0.05\textwidth}"}
\ 
:::::::::

::::::::: {.col data-latex="{0.75\textwidth}"}

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.4\textwidth}"}
### [\faGithub \ Ephemeral Chat](https://github.com/happyRip/Ephemeral-Chat)
:::

::: {.col data-latex="{0.05\textwidth}"}
\ 
:::

::: {.col data-latex="{0.55\textwidth}"}
> *try me at [\Mundus chat.happy.rip](https://chat.happy.rip/)*
:::

::::::

\qquad Creating this website I wanted to make a chat application that would be quick to start using.
I wanted to introduce a Continuous Deployment workflow which I did utilizing GitHub Actions and Docker.
To create a live-chat experience I used Phoenix framework with LiveView behaviour.
/ /
:::::::::

::::::::::::

:::::::::::: {.cols data-latex=""}

::::::::: {.col data-latex="{0.2\textwidth}"}
2020 - 2022

#### Technologies:

Go *([Sciter](https://sciter.com/))*
:::::::::

::::::::: {.col data-latex="{0.05\textwidth}"}
\ 
:::::::::

::::::::: {.col data-latex="{0.75\textwidth}"}

:::::: {.cols data-latex=""}
::: {.col data-latex="{0.4\textwidth}"}
### [\faGithub \ Box Tailor](https://github.com/happyRip/Box-Tailor-Go)
:::

::: {.col data-latex="{0.05\textwidth}"}
\ 
:::

::: {.col data-latex="{0.55\textwidth}"}
> *Parametric box design*
:::
::::::

\qquad An app than can be used to create and export boxes based on product measurements given. The templates arose are then optimally fitted onto boards of given dimensions. This way the whole template can then be cut on a laser cutter or cnc plotter, allowing small businesses to have their own custom box solution.
\ \
:::::::::

::::::::::::

---

:::::: {.cols data-latex=""}

::: {.col data-latex="{0.47\textwidth}"}
## Skills

- Go *(test, [Sciter,](https://sciter.com/) [Cobra](https://github.com/spf13/cobra), [Bubbletea,](https://github.com/charmbracelet/bubbletea) [go-chi](https://github.com/go-chi/chi), [go.uuid](https://github.com/satori/go.uuid))*
- Elixir *([Phoenix](https://www.phoenixframework.org/))*
- Python *(numpy, pandas, matplotlib)*
- [Jenkins](https://www.jenkins.io/), [Groovy](https://groovy-lang.org/)
- UNIX, bash, vim, ssh, tmux, make
- [Docker](https://www.docker.com/), [GitHub Actions](https://github.com/features/actions)
- JavaScript *([certificate](https://www.freecodecamp.org/certification/happyrip/javascript-algorithms-and-data-structures))*, C++ *(std)*
\ \
:::

::: {.col data-latex="{0.13\textwidth}"}
\ 
:::

::: {.col data-latex="{0.4\textwidth}"}
## Languages

- Polish – *native*
- English – *professional*
- German – *elementary*

## Interests

- [Computer Aided Design](https://en.wikipedia.org/wiki/Computer-aided_design)
- Electronics and Tinkering
- Graphic design, photography
:::

::::::
