name: Render resume
on: 
  push:
    paths:
      - 'Resume.Rmd'
      - 'columns.tex'
      - '.github/workflows/*'
jobs:
  render-document:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: happyRip/rmarkdown-action@v1.1
        with:
          input_file: Resume.Rmd
          output_format: pdf_document
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git add *.pdf && git add --renormalize *.pdf
          git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
          git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
          NO_PAGER=1 git --no-pager diff HEAD^
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: layout-improvements-test 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
