name: Render
on: 
  push:
    paths:
      - 'Resume.Rmd'
      - 'columns.tex'
      - '.github/workflows/*'
jobs:
  render:
    name: Render document
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Render document
        uses: happyRip/rmarkdown-action@v1.1
        with:
          input_file: Resume.Rmd
          output_format: pdf_document
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Resume
          path: Resume.pdf
